### ISSUE TITLE
Do you use non standard functionality?

### ISSUE THREAD

**Issue by FalkoSp** [bshoshany/spacetime-diagrams#1]
I just downloaded the player, version 13.0.1.0 (Win). With great melancholy I see the "Why the beep?" window. 
(The single functionality of Mathematica I mention to friends and collegues regularly, after all those years without using it.)

![image](https://user-images.githubusercontent.com/80770003/172206174-efcede17-0b90-419b-931e-acfe763c6555.png)

It seems you use something unorthodox.

Kind greetings, f.

**Comment by bshoshany** [comment]
You're right, this doesn't seem to actually work with Wolfram Player. My understanding was that it should work, but I guess it doesn't :disappointed: I'll look into it.

**Comment by bshoshany** [comment]
Thanks for opening this issue! Apparently, there was a weird bug that prevented the notebook from working with Wolfram Player. This bug is now fixed in v1.0.1. Please let me know if it works for you.

**Comment by FalkoSp** [comment]
Sorry for the delay, I was sort of offline during the weekend.
Thank you! It opens now!
I still need to understand what it is demonstrating, hope to find time this evening.
Kind greetings, f.
